"""make changes to post table2

Revision ID: 9990de813926
Revises: 60719d1b2b19
Create Date: 2025-08-30 02:31:49.103759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9990de813926'
down_revision: Union[str, Sequence[str], None] = '60719d1b2b19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['user_id'])
    op.add_column('users', sa.Column('user_number', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'users', ['user_number'])
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'user_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'email')
    op.drop_column('users', 'user_number')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'user_id')
    # ### end Alembic commands ###
